version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      next-react:
        patterns:
          - "next"
          - "react"
          - "react-dom"
      tauri-js:
        patterns:
          - "@tauri-apps/*"
          - "@crabnebula/tauri-plugin-drag"

  - package-ecosystem: cargo
    directory: "/apps/desktop/src-tauri"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      tauri-rust:
        patterns:
          - "tauri"
          - "tauri-*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
