export type LandingLocale = "tr" | "en";

export const landingCopy = {
  tr: {
    nav: {
      studio: "Canlı Stüdyo",
      features: "Özellikler",
      workflow: "İş Akışı",
      privacy: "Gizlilik",
      faq: "SSS",
      download: "İndir",
      hubLink: "AtrisHub ↗",
    },
    language: { label: "Dil seçimi", tr: "Türkçe", en: "English" },
    theme: { light: "Açık temaya geç", dark: "Koyu temaya geç" },
    hero: {
      eyebrow: "ATRIS EKOSİSTEMİ · v1.0.1 HAZIR",
      title: "Piksel hassasiyetinde yakala. Anında paylaş.",
      description:
        "AtrisShot, ekran görüntüsünü akışını bölmeden yakalayıp işaretlemeni sağlayan profesyonel bir Tauri masaüstü stüdyosudur. Manyetik pencere tespiti, vektörel notlar ve akıllı sansürleme ile görseller doğrudan panoda ve dosya yolunda hazır.",
      primaryDownload: "İndir",
      watchFilm: "Ürün Filmini İzle",
      filmDuration: "24sn",
      badges: [
        "Ücretsiz Atris Hesabı",
        "%100 Yerel ve Çevrimdışı",
        "Sıfır Bulut Sızıntısı",
        "İmzalı Windows, Mac & Linux",
      ],
      update: "Tauri v2 İmzalı Otomatik Güncelleme Kanalı",
    },
    platform: {
      windows: "Windows İçin İndir",
      mac: "macOS (Yakında)",
      linux: "Linux İçin İndir",
      windowsDetail: "Windows 10 / 11 (x64) · .msi & .exe",
      macDetail: "macOS paketi Apple imzalama anahtarları hazır olduğunda eklenecek.",
      linuxDetail: "Linux (x64) · .AppImage & .deb",
      macPaused: "macOS paketi Apple imzalama anahtarları hazır olduğunda eklenecek.",
    },
    sandbox: {
      windowTitle: "AtrisShot Studio — Örnek Görünüm",
      freeBadge: "ÜCRETSİZ",
      tabSnap: "Manyetik Snap",
      tabAnnotate: "Vektörel Notlar",
      tabBlur: "Akıllı Sansür",
      tabOutput: "Pano & Handoff",
      snapHint: "Pencereler üzerine tıkla ve manyetik kilitlenmeyi gör",
      snapButton: "⚡ Alanı Dondur & Yakala",
      annotateHint: "Renk paleti veya araç seç · Çizimleri anında dene",
      blurHint: "Kaydırıcıyı sürükle · Tersine çevrilemez pikselasyon",
      blurIntensity: "Sansürleme Yoğunluğu",
      blurSafeNote: "0 KB Bulut Yüklemesi · Rust matrisinde kalıcı olarak yakılır",
      outputHint: "Çıktı formatını seç · Panoya kopyala veya handoff yap",
      tools: {
        select: "Seçim",
        crop: "Kırpma",
        arrow: "Yön Oku",
        rect: "Kutu",
        blur: "Sansür / Blur",
        copyImage: "Resmi Kopyala",
        copyPath: "Path'i Kopyala",
      },
      cropStatus: "1920 × 1080 Hassas Alan",
      snapBadge: "Manyetik Kilitlenme Aktif",
      dragHint: "Aktif sekmeyi değiştir veya tuval üzerindeki araçları dene",
      codeSnippetTitle: "auth_config.json — Canlı Veri Görünümü",
      apiKeyLabel: "api_secret_key:",
      redactedText: "••••••••••••••••••••••••••••••••",
      annotationLabel: "Canlı API Uç Noktası ↗",
      rectLabel: "Kimlik Doğrulama Bloğu",
      redactedLabel: "Tersine Çevrilemez Sansür",
      cornerStackTitle: "AtrisShot Hızlı Önizleme",
      cornerStackHandoff: "Sürükle-Bırak Handoff Hazır",
      toastImage: "Görsel panoya kopyalandı! (image/png) 📋",
      toastPath: "Dosya yolu kopyalandı: C:\\AtrisShot\\shot-01.png 📁",
      toastSnap: "Manyetik alan yakalandı ve donduruldu! ⚡",
      reset: "Varsayılana Sıfırla",
      interactiveBadge: "CANLI ETKİLEŞİMLİ STÜDYO",
    },
    bento: {
      eyebrow: "MÜHENDİSLİK VE MASAÜSTÜ GÜCÜ",
      title: "Sıradan bir ekran aracı değil. Eksiksiz bir stüdyo.",
      subtitle:
        "Tauri v2 ve Rust çekirdeği ile 15MB'ın altında bellek tüketimi, sıfır gecikme ve derin işletim sistemi entegrasyonu.",
      card1: {
        tag: "AKILLI SINIR ALGILAMA",
        title: "Manyetik Pencere ve Çoklu Monitör Tespiti",
        desc: "Çoklu monitör kurulumlarında (4K monitör + dizüstü ekranı) yaşanan DPI ölçekleme bozulmalarına son. İmlecin altındaki aktif pencereyi milisaniyeler içinde algılar; işletim sistemi pencere ağacına manyetik olarak kilitlenir.",
        subtext: "Pencerelerin sınırlarını otomatik yakalar; piksel kayması olmadan tam çerçeve alır.",
        interactiveHint: "Canlı pencereye tıkla ve manyetik kilitlenmeyi gör:",
        badgeAdaptive: "DPI Adaptive 100% - 200%",
        badgeWindowSnap: "Manyetik Snap Aktif",
      },
      card2: {
        tag: "KRİPTOGRAFİK GÜVENLİK",
        title: "Piksel Düzeyinde Güvenli Sansürleme (Blur)",
        desc: "API anahtarlarını, şifreleri ve gizli müşteri bilgilerini geçici CSS filtreleriyle değil; Rust piksel matrisinde geri döndürülemez şekilde yakarak sansürleyin. Dışa aktarılan görselden verinin geri çözülmesi imkansızdır.",
        sliderLabel: "Sansürleme Yoğunluğu",
        badgeRedacted: "Tersine Çevrilemez Pikselasyon",
        safeNote: "Ham veri piksel seviyesinde kalıcı olarak yok edilir.",
        redactedStamp: "KALICI SANSÜRLENDİ",
      },
      card3: {
        tag: "GELİŞTİRİCİ & AI İŞ AKIŞI",
        title: "Çift Çıktı Pipeline'ı (Bitmap + Yerel Path)",
        desc: "Tasarımcılar Figma ve Slack için panoda doğrudan görsel baytlarına (image/png) ihtiyaç duyar; yazılımcılar, terminal ve AI ajanları (Cursor, Claude, AtrisAgent) ise dosya yoluna (file://). AtrisShot ikisini de aynı anda hazır tutar.",
        tabImageTitle: "Tasarım & Sohbet (Figma, Slack)",
        tabImageDesc: "Panoya doğrudan bitmap PNG kopyalanır. Ctrl+V ile yapıştırın.",
        tabPathTitle: "Terminal & AI (Cursor, Agent)",
        tabPathDesc: "Yerel dosya yolu (file:///C:/...) kopyalanır. AI komutlarına sürükleyin.",
        copiedImageToast: "PNG Bitmap Panoya Kopyalandı (image/png)",
        copiedPathToast: "Yerel Dosya Yolu Kopyalandı (file:///...)",
        testHint: "Test etmek için bir pipeline seçeneğine tıklayın",
      },
      card4: {
        tag: "SÜRTÜNMESİZ HANDOFF",
        title: "Doğrudan Sürükle-Bırak Dosya Aktarımı",
        desc: "Ekran alıntısı aldıktan sonra İndirilenler klasöründe dosya arama derdine son. Önizleme kartını tutup doğrudan Slack kanalına, GitHub PR yorumuna, Jira biletine veya Figma tuvaline fiziksel bir .png dosyası gibi bırakın.",
        dropHint: "tauri-plugin-drag ile gerçek işletim sistemi dosya işaretçisi",
        targetList: "GitHub PR · Slack · Discord · Jira · Figma",
      },
      card5: {
        tag: "ENTERPRISE GİZLİLİK",
        title: "%100 Cihaz Üzerinde, Sıfır Bulut Bağımlılığı",
        desc: "Bulut tabanlı ekran yakalama araçları şirket kodunuzu veya müşteri verilerinizi uzak sunuculara yükler. AtrisShot'ta hiçbir görsel internete çıkmaz; tüm veriler yerel diskinizde, Windows DPAPI ve macOS Keychain korumasıyla saklanır.",
        statCloud: "0 KB Bulut Yüklemesi",
        statOffline: "Tam Çevrimdışı Çalışma",
        statDb: "Yerel Şifreli SQLite Geçmişi",
      },
    },
    workflow: {
      eyebrow: "SÜRTÜNMESİZ AKIŞ",
      title: "3 adımda odaktan kopmadan tamamla.",
      steps: [
        {
          num: "01",
          title: "Odaklı yakalama & Tetikleme",
          desc: "Kısayoluna bas; manyetik pencere veya odaklı yakalama ile alanı anında dondur.",
        },
        {
          num: "02",
          title: "Netleştir ve Sansürle",
          desc: "Vektörel ok, kutu, metin ve akıllı blur araçlarıyla ekibin için bağlamı anında açık hale getir.",
        },
        {
          num: "03",
          title: "Akışa Bırak",
          desc: "Görseli panoya kopyala veya dosya kartını sürükleyerek doğrudan çalışma alanına bırak.",
        },
      ],
    },
    privacy: {
      eyebrow: "GİZLİLİK VE MİMARİ",
      title: "Görselleriniz yalnızca sizin cihazınızda yaşar.",
      description:
        "AtrisHub altyapısı yalnızca ilk oturum açma ve lisans doğrulaması için kullanılır. Ekran görüntüleri, çizimler ve geçmiş dosyaları yerel diskinde saklanır; internet olmasa dahi çevrimdışı toleransla çalışmaya devam eder.",
      cards: [
        {
          title: "Ücretsiz Atris Hesabı",
          desc: "Tüm temel özellikler ücretsizdir; kredi kartı veya abonelik gerekmez.",
        },
        {
          title: "Yerel SQLite Geçmişi",
          desc: "Geçmiş yakalamalar sadece cihazındaki güvenli yerel veritabanında tutulur.",
        },
        {
          title: "Sıfır Telemetri",
          desc: "Görsel verisi, piksel içeriği veya dosya isimleri asla dışarı sızdırılmaz.",
        },
      ],
    },
    faq: {
      eyebrow: "MERAK EDİLENLER",
      title: "Sıkça Sorulan Sorular",
      subtitle:
        "AtrisShot'ın özellikleri, gizlilik mimarisi, desteklenen platformlar ve ekosistem entegrasyonu hakkında merak ettiğiniz her şey.",
      items: [
        {
          q: "AtrisShot gerçekten tamamen ücretsiz mi? Herhangi bir gizli abonelik var mı?",
          a: "Evet, AtrisShot Atris ekosisteminin ücretsiz bir parçasıdır. Herhangi bir ekran görüntüsü yakalama sınırlaması, watermark (filigran) veya gizli abonelik ücreti bulunmamaktadır. Tek ihtiyacınız olan ücretsiz bir AtrisHub hesabıdır.",
        },
        {
          q: "Ekran görüntülerim buluta yükleniyor mu? Şirket gizlilik politikalarına uygun mu?",
          a: "Kesinlikle hayır. AtrisShot %100 yerel-first (Local-First) prensibiyle çalışır. Çektiğiniz hiçbir ekran görüntüsü, işaretleme veya dosya adı harici sunuculara iletilmez. Tüm veriler yalnızca kendi bilgisayarınızda saklanır; kurumsal gizlilik ve KVKK/GDPR uyumluluğu tamdır.",
        },
        {
          q: "macOS, Windows ve Linux sürümleri arasında özellik farkı var mı?",
          a: "Hayır. AtrisShot'ın çekirdeği Rust ve Tauri v2 üzerine inşa edildiği için Windows 10/11, macOS (Apple Silicon M1/M2/M3/M4 & Intel) ve Linux dağıtımlarında birebir aynı profesyonel yetenekleri (manyetik pencere yakalama, vektörel çizim, akıllı blur ve çift çıktı) yerel hızda sunar.",
        },
        {
          q: "Geliştiriciler ve yapay zeka araçları (Cursor, Claude, AtrisAgent) için dosya yolu (path) çıktısı nasıl çalışır?",
          a: "AtrisShot ile bir görüntü aldığınızda hem görselin kendisi panonuza kopyalanır hem de dosyanın yerel yolu (örn. C:\\Users\\...\\shot.png veya file:///...) anında hazır olur. Böylece terminalde bir komuta argüman olarak verebilir veya Cursor/Claude/AtrisAgent prompt alanına doğrudan yapıştırabilirsiniz.",
        },
        {
          q: "Akıllı sansürleme (Blur) aracı güvenlik açısından ne kadar güvenilir? Geri çözülebilir mi?",
          a: "AtrisShot'ın sansürleme aracı, görsel üzerinde sadece şeffaf bir katman oluşturmaz; Rust grafik motoru seviyesinde ilgili piksel matrisini matematiksel olarak yok edip homojen bloklara dönüştürür. Bu nedenle dışa aktarılan PNG dosyasından sansürlenmiş veriyi geri getirmek imkansızdır.",
        },
        {
          q: "Klavye kısayollarını, kayıt klasörünü ve köşe önizlemesini özelleştirebilir miyim?",
          a: "Evet. Masaüstü uygulamasının Ayarlar panelinden global yakalama kısayolunuzu, ekran görüntülerinin kaydedileceği yerel dizini, otomatik dosya adlandırma şablonlarını ve yakalama sonrasında çıkan köşe önizleme çubuğunun davranışını (otomatik gizlenme, köşe konumu) tamamen kişiselleştirebilirsiniz.",
        },
      ],
      contactPrompt: "Aradığınız cevabı bulamadınız mı?",
      contactLink: "GitHub Topluluğuna ve Desteğe Ulaşın ↗",
    },
    download: {
      eyebrow: "KURULUM",
      title: "AtrisShot'ı bugün kullanmaya başla.",
      description:
        "Windows, macOS ve Linux için yerel derlenmiş ikili paketler. Hızlı kurulum, arka planda otomatik güncelleme ve tam sistem uyumu.",
      cardWindows: {
        title: "Windows 10 / 11",
        version: "v1.0.1 (x64)",
        type: "MSI Yükleyici & Taşınabilir EXE",
        badge: "Önerilen",
      },
      cardMac: {
        title: "macOS",
        version: "Apple Silicon & Intel",
        type: "macOS paketi yakında yayınlanacak",
        badge: "Yakında",
      },
      cardLinux: {
        title: "Linux Dağıtımları",
        version: "v1.0.1 (x64)",
        type: "AppImage & Debian (.deb)",
        badge: "Topluluk",
      },
      signedBadge: "Dijital İmzalı Paket",
      freeBadge: "Ücretsiz Kullanım",
      hubAccountBadge: "AtrisHub SSO Uyumlu",
    },
    film: {
      scenes: [
        ["MANYETİK YAKALAMA", "Pencere sınırlarını milisaniyede algıla ve anında dondur.", "Tauri Overlay"],
        ["VEKTÖREL EDİTÖR", "Ok, kutu, metin ve renk paletiyle bağlamı anında netleştir.", "Shot Editor Studio"],
        ["KRİPTOGRAFİK SANSÜR", "Hassas anahtarları Rust piksel motorunda kalıcı olarak yok et.", "Irreversible Redact"],
        ["ÇİFT ÇIKTI & HANDOFF", "Panoya kopyala, path'i al veya doğrudan Slack/PR'a sürükle.", "Clipboard + Drag Handoff"],
      ] as const,
      footer: "Ücretsiz Atris hesabı için yerel ekran görüntüsü stüdyosu",
      music: "Orijinal AtrisShot Tanıtım Teması (Ambient · 68 BPM)",
    },
    filmModal: {
      title: "AtrisShot — Ürün Tanıtım Filmi",
      description: "AtrisShot masaüstü deneyimini ve akışını 24 saniyelik sinematik anlatımla izleyin.",
      close: "Kapat",
      musicCredit: "Orijinal AtrisShot Tema Müziği (Slow Ambient · 68 BPM)",
    },
    footer: {
      descriptor:
        "Geliştirmeden proje sürekliliğine, tek bir Atris ekosistemi. AtrisShot, piksel hassasiyetinde ve yerel-first masaüstü ekran yakalama stüdyosudur.",
      productsLabel: "Atris Ekosistemi",
      exploreLabel: "Sayfa İçi Gezinti",
      accountLabel: "AtrisHub Hesabını Yönet",
      rights: "© 2026 AtrisShot. Tüm hakları saklıdır.",
      builtBy: "Built by E. Mert EREN",
    },
    ecosystemProducts: [
      { label: "AtrisHub", href: "https://atrishub.com" },
      { label: "AtrisChat", href: "https://chat.atrishub.com" },
      { label: "AtrisAgent", href: "https://agent.atrishub.com" },
      { label: "AtrisWork", href: "https://work.atrishub.com" },
      { label: "AtrisBridge", href: "https://bridge.atrishub.com" },
      { label: "AtrisVoice", href: "https://voice.atrishub.com" },
      { label: "AtrisTracker", href: "https://atrishub.com/products/tracker" },
      { label: "AtrisCast", href: "https://atrishub.com/products/cast" },
    ],
  },
  en: {
    nav: {
      studio: "Live Studio",
      features: "Features",
      workflow: "Workflow",
      privacy: "Privacy",
      faq: "FAQ",
      download: "Download",
      hubLink: "AtrisHub ↗",
    },
    language: { label: "Select language", tr: "Türkçe", en: "English" },
    theme: { light: "Switch to light theme", dark: "Switch to dark theme" },
    hero: {
      eyebrow: "ATRIS ECOSYSTEM · v1.0.1 READY",
      title: "Capture with pixel precision. Share without friction.",
      description:
        "AtrisShot is a professional Tauri desktop studio designed to capture and annotate screenshots without breaking flow. Magnetic window snapping, vector annotations, and smart pixelate blur keep your work ready in your clipboard and file path.",
      primaryDownload: "Download",
      watchFilm: "Watch Product Film",
      filmDuration: "24s",
      badges: [
        "Free Atris Account",
        "100% Local & Offline",
        "Zero Cloud Leakage",
        "Signed Windows, Mac & Linux",
      ],
      update: "Tauri v2 Signed Auto-Update Channel",
    },
    platform: {
      windows: "Download for Windows",
      mac: "macOS (Coming Soon)",
      linux: "Download for Linux",
      windowsDetail: "Windows 10 / 11 (x64) · .msi & .exe",
      macDetail: "macOS packages will return when Apple signing keys are ready.",
      linuxDetail: "Linux (x64) · .AppImage & .deb",
      macPaused: "macOS packages will return when Apple signing keys are ready.",
    },
    sandbox: {
      windowTitle: "AtrisShot Studio — Sample Preview",
      freeBadge: "FREE",
      tabSnap: "Magnetic Snap",
      tabAnnotate: "Vector Annotate",
      tabBlur: "Smart Redact",
      tabOutput: "Clipboard & Handoff",
      snapHint: "Click mock windows to test instant magnetic frame lock",
      snapButton: "⚡ Freeze & Capture Area",
      annotateHint: "Pick color palette or tools · Test live annotations",
      blurHint: "Drag slider · Cryptographic irreversible pixelation",
      blurIntensity: "Redaction Density",
      blurSafeNote: "0 KB Cloud Traffic · Erased permanently in Rust raster matrix",
      outputHint: "Select format · Copy to clipboard or drag handoff",
      tools: {
        select: "Select",
        crop: "Crop",
        arrow: "Arrow",
        rect: "Rectangle",
        blur: "Censor / Blur",
        copyImage: "Copy Image",
        copyPath: "Copy Path",
      },
      cropStatus: "1920 × 1080 Precision Bounds",
      snapBadge: "Magnetic Snap Active",
      dragHint: "Switch active tab or interact with studio tools above",
      codeSnippetTitle: "auth_config.json — Live Data Inspector",
      apiKeyLabel: "api_secret_key:",
      redactedText: "••••••••••••••••••••••••••••••••",
      annotationLabel: "Live API Endpoint ↗",
      rectLabel: "Authentication Scope",
      redactedLabel: "Irreversible Redaction",
      cornerStackTitle: "AtrisShot Quick Preview",
      cornerStackHandoff: "Drag-and-Drop Handoff Ready",
      toastImage: "Image copied to clipboard! (image/png) 📋",
      toastPath: "File path copied: C:\\AtrisShot\\shot-01.png 📁",
      toastSnap: "Magnetic area captured and frozen! ⚡",
      reset: "Reset to Default",
      interactiveBadge: "LIVE INTERACTIVE STUDIO",
    },
    bento: {
      eyebrow: "ENGINEERING & DESKTOP POWER",
      title: "Not just a screenshot tool. A complete studio.",
      subtitle:
        "Engineered with Rust and Tauri v2 for sub-15MB memory footprint, zero latency, and deep OS integration.",
      card1: {
        tag: "INTELLIGENT BOUNDS",
        title: "Magnetic Window & Multi-Display Detection",
        desc: "End the struggle with DPI scaling distortions across mixed setups (4K external monitor + laptop screen). Instantly detects the window beneath your cursor and snaps magnetically to OS window frames with zero pixel bleed.",
        subtext: "Captures full native resolution with crisp borders and zero manual trimming.",
        interactiveHint: "Click mock windows to test magnetic snapping:",
        badgeAdaptive: "DPI Adaptive 100% - 200%",
        badgeWindowSnap: "Magnetic Snap Active",
      },
      card2: {
        tag: "CRYPTOGRAPHIC SECURITY",
        title: "Pixel-Level Irreversible Redaction (Blur)",
        desc: "Never rely on flimsy CSS masks that can be inspected or reversed. AtrisShot destructively bakes pixelation directly into the image raster matrix inside the Rust engine, making recovery mathematically impossible.",
        sliderLabel: "Redaction Density",
        badgeRedacted: "Irreversible Redaction",
        safeNote: "Raw pixel data is permanently erased in memory before saving.",
        redactedStamp: "IRREVERSIBLY REDACTED",
      },
      card3: {
        tag: "DEVELOPER & AI PIPELINE",
        title: "Dual Output Pipeline (Bitmap + Local Path)",
        desc: "Designers paste visual images directly into Figma and Slack; engineers, terminals, and AI agents (Cursor, Claude, AtrisAgent) need exact file URIs (file://). AtrisShot delivers both concurrently with zero manual saving.",
        tabImageTitle: "Design & Chat (Figma, Slack)",
        tabImageDesc: "Raw bitmap image copied to clipboard. Ready for Ctrl+V.",
        tabPathTitle: "Code & AI Agents (Cursor, Agent)",
        tabPathDesc: "Local file path (file:///...) copied. Ready for AI prompt context.",
        copiedImageToast: "PNG Bitmap Copied to Clipboard (image/png)",
        copiedPathToast: "Local File Path Copied (file:///...)",
        testHint: "Click an option above to test output pipeline",
      },
      card4: {
        tag: "FRICTIONLESS HANDOFF",
        title: "Direct Drag & Drop File Handoff",
        desc: "Stop hunting through your Downloads folder. When you take a shot, the floating preview thumbnail acts as a native OS file pointer. Grab it and drop it directly into GitHub PR comments, Jira tickets, or Slack channels as a real .png file.",
        dropHint: "Native OS file descriptor via tauri-plugin-drag",
        targetList: "GitHub PR · Slack · Discord · Jira · Figma",
      },
      card5: {
        tag: "ENTERPRISE PRIVACY",
        title: "100% On-Device, Zero Cloud Dependence",
        desc: "Cloud screenshot apps upload your confidential code and customer PII to remote servers. With AtrisShot, not a single byte leaves your machine; everything stays encrypted on local disk with Windows DPAPI and macOS Keychain.",
        statCloud: "0 KB Cloud Traffic",
        statOffline: "Full Offline Capability",
        statDb: "Encrypted SQLite History",
      },
    },
    workflow: {
      eyebrow: "FRICTIONLESS FLOW",
      title: "Three steps. Zero context switching.",
      steps: [
        {
          num: "01",
          title: "Focused capture & Trigger",
          desc: "Press your shortcut; freeze active windows instantly with focused capture.",
        },
        {
          num: "02",
          title: "Annotate & Censor",
          desc: "Clarify context for your team using vector arrows, rectangles, text, and smart blur tools.",
        },
        {
          num: "03",
          title: "Place in Workflow",
          desc: "Copy the image to clipboard or drag the file card straight into your workspace.",
        },
      ],
    },
    privacy: {
      eyebrow: "PRIVACY & ARCHITECTURE",
      title: "Your screenshots belong only on your device.",
      description:
        "AtrisHub infrastructure is used strictly for initial login and membership verification. Screenshots, annotations, and history files live in local storage, operating reliably even offline.",
      cards: [
        {
          title: "Free Atris Account",
          desc: "All core features are free; no subscription or credit card required.",
        },
        {
          title: "Local SQLite History",
          desc: "Capture history is stored only in a secure local database on your machine.",
        },
        {
          title: "Zero Telemetry",
          desc: "Image contents, pixels, and file paths are never monitored or transmitted.",
        },
      ],
    },
    faq: {
      eyebrow: "QUESTIONS & ANSWERS",
      title: "Frequently Asked Questions",
      subtitle:
        "Everything you need to know about AtrisShot's desktop capabilities, security model, and platform support.",
      items: [
        {
          q: "Is AtrisShot really completely free? Are there any hidden subscriptions or watermarks?",
          a: "Yes, AtrisShot is a free tier application in the Atris ecosystem. There are no capture count limits, no watermarks, and no hidden subscriptions. All you need is a free AtrisHub account to get started.",
        },
        {
          q: "Do my screenshots get uploaded to the cloud? Is it compliant with privacy policies?",
          a: "Never. AtrisShot operates on a strict Local-First architecture. No screenshots, annotations, or file metadata are ever transmitted to remote servers. All assets reside on your local machine, fully compliant with enterprise privacy and GDPR requirements.",
        },
        {
          q: "Are there feature differences between macOS, Windows, and Linux?",
          a: "No. Because AtrisShot's engine is built with Rust and Tauri v2, all platforms (Windows 10/11, macOS Apple Silicon/Intel, Linux distributions) offer the exact same desktop capabilities (magnetic snapping, vector markup, irreversible blur, and dual clipboard output) at native speed.",
        },
        {
          q: "How does the file path output work for developers and AI assistants (Cursor, Claude, AtrisAgent)?",
          a: "When you take a capture, AtrisShot can automatically copy the local file path (e.g. C:\\Users\\...\\shot.png or file:///...) to your clipboard. You can paste it directly into Cursor, VS Code terminal, or AI assistant prompts with zero manual navigation.",
        },
        {
          q: "How secure is the pixelation (Blur) tool? Can censored data be reversed or reconstructed?",
          a: "AtrisShot's blur tool does not apply a reversible CSS overlay. The Rust graphics pipeline destructively replaces the underlying pixel grid with averaged mosaic blocks before encoding the PNG. It is mathematically impossible to reconstruct the original data from the resulting image.",
        },
        {
          q: "Can I customize shortcuts, output directories, and the result overlay?",
          a: "Yes. In the application Settings panel, you can customize your global hotkey, the local directory where screenshots are saved, file naming templates, and how the corner result overlay behaves (auto-hide delay, anchor corner).",
        },
      ],
      contactPrompt: "Have another question or feature request?",
      contactLink: "Reach out to the GitHub community & support ↗",
    },
    download: {
      eyebrow: "GET STARTED",
      title: "Start using AtrisShot today.",
      description:
        "Optimized native binaries for Windows, macOS, and Linux. Fast setup, background auto-updates, and native performance.",
      cardWindows: {
        title: "Windows 10 / 11",
        version: "v1.0.1 (x64)",
        type: "MSI Installer & Portable EXE",
        badge: "Recommended",
      },
      cardMac: {
        title: "macOS",
        version: "Apple Silicon & Intel",
        type: "macOS packages will return soon",
        badge: "Coming Soon",
      },
      cardLinux: {
        title: "Linux Distributions",
        version: "v1.0.1 (x64)",
        type: "AppImage & Debian (.deb)",
        badge: "Community",
      },
      signedBadge: "Digitally Signed Package",
      freeBadge: "Free Forever Tier",
      hubAccountBadge: "AtrisHub SSO Compatible",
    },
    film: {
      scenes: [
        ["MAGNETIC CAPTURE", "Detect window boundaries with sub-pixel precision in milliseconds.", "Tauri Overlay"],
        ["VECTOR STUDIO", "Clarify context instantly with arrows, boxes, text, and swatches.", "Shot Editor Studio"],
        ["CRYPTOGRAPHIC REDACT", "Destroy sensitive API keys permanently in Rust pixel raster.", "Irreversible Redact"],
        ["DUAL OUTPUT & HANDOFF", "Copy PNG bitmap, grab local file URI, or drag directly to Slack/PR.", "Clipboard + Drag Handoff"],
      ] as const,
      footer: "A local screenshot studio for free Atris accounts",
      music: "Original AtrisShot Promo Theme (Ambient · 68 BPM)",
    },
    filmModal: {
      title: "AtrisShot — Product Film",
      description: "Experience the AtrisShot desktop workflow in a 24-second cinematic breakdown.",
      close: "Close",
      musicCredit: "Original AtrisShot Theme Music (Slow Ambient · 68 BPM)",
    },
    footer: {
      descriptor:
        "From development to project continuity, one Atris ecosystem. AtrisShot is a local-first screenshot capture and markup studio.",
      productsLabel: "Atris Ecosystem",
      exploreLabel: "On-Page Navigation",
      accountLabel: "Manage AtrisHub Account",
      rights: "© 2026 AtrisShot. All rights reserved.",
      builtBy: "Built by E. Mert EREN",
    },
    ecosystemProducts: [
      { label: "AtrisHub", href: "https://atrishub.com" },
      { label: "AtrisChat", href: "https://chat.atrishub.com" },
      { label: "AtrisAgent", href: "https://agent.atrishub.com" },
      { label: "AtrisWork", href: "https://work.atrishub.com" },
      { label: "AtrisBridge", href: "https://bridge.atrishub.com" },
      { label: "AtrisVoice", href: "https://voice.atrishub.com" },
      { label: "AtrisTracker", href: "https://atrishub.com/products/tracker" },
      { label: "AtrisCast", href: "https://atrishub.com/products/cast" },
    ],
  },
} as const;
